# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='static/imgs/banner/', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=256, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='kecheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='static/imgs/kecheng', verbose_name='课程介绍')),
                ('title', models.CharField(default='', max_length=64, verbose_name='课程标题')),
                ('content', models.TextField(verbose_name='课程内容')),
            ],
            options={
                'verbose_name_plural': '课程介绍',
                'verbose_name': '课程介绍',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='static/imgs/teacher', verbose_name='教师')),
                ('name', models.CharField(max_length=64, verbose_name='教师名字')),
            ],
        ),
        migrations.CreateModel(
            name='wenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='问题讨论')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('cover', models.ImageField(upload_to='static/imgs/wenti/', verbose_name='炮制数据库')),
            ],
            options={
                'verbose_name_plural': '问题讨论',
                'verbose_name': '问题讨论',
            },
        ),
    ]
