# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师认证', 'verbose_name_plural': '教师认证'},
        ),
        migrations.RemoveField(
            model_name='wenti',
            name='cover',
        ),
        migrations.AlterField(
            model_name='kecheng',
            name='cover',
            field=models.ImageField(upload_to='static/imgs/kecheng', verbose_name='课程介绍图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cover',
            field=models.ImageField(upload_to='static/imgs/teacher', verbose_name='教师图片'),
        ),
        migrations.AlterField(
            model_name='wenti',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='具体问题'),
        ),
    ]
