# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190517_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='jieshao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='static/imgs/jieshao', verbose_name='课程介绍图片')),
                ('title', models.CharField(max_length=64, verbose_name='书籍标题')),
                ('content', models.TextField(verbose_name='书籍简介')),
            ],
            options={
                'verbose_name': '课程介绍',
                'verbose_name_plural': '课程介绍',
            },
        ),
    ]
