# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jieshao'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiangqing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='static/imgs/xiangqing', verbose_name='课程介绍详情图片')),
                ('content', models.TextField(verbose_name='课程介绍详情内容')),
            ],
            options={
                'verbose_name_plural': '课程介绍详情',
                'verbose_name': '课程介绍详情',
            },
        ),
        migrations.AlterModelOptions(
            name='jieshao',
            options={'verbose_name': '课程介绍列表', 'verbose_name_plural': '课程介绍列表'},
        ),
    ]
